version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: nopmocounter-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3311:3306"