version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: nopmo
    ports:
      - "3311:3306"
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge